<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class AddMoreProductsSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Tas Ransel
            [
                'category_id' => 1,
                'name' => 'Tas Ransel Laptop Gaming',
                'slug' => 'tas-ransel-laptop-gaming',
                'description' => 'Ransel khusus untuk laptop gaming dengan padding tebal dan desain futuristik. Dilengkapi USB charging port.',
                'price' => 550000,
                'discount_price' => 499000,
                'stock' => 20,
                'image' => 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=400&h=400&fit=crop',
                'brand' => 'GamerPack',
                'material' => 'Ballistic Nylon',
                'color' => 'Hitam/Merah',
                'size' => '48 x 32 x 18 cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Tas Ransel Sekolah Anak',
                'slug' => 'tas-ransel-sekolah-anak',
                'description' => 'Ransel ergonomis untuk anak sekolah dengan desain colorful dan bahan ringan namun kuat.',
                'price' => 280000,
                'discount_price' => 249000,
                'stock' => 35,
                'image' => 'https://images.unsplash.com/photo-1577655197620-704858b270ac?w=400&h=400&fit=crop',
                'brand' => 'KidsBag',
                'material' => 'Polyester',
                'color' => 'Biru/Kuning',
                'size' => '38 x 28 x 12 cm',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Tas Ransel Outdoor Adventure',
                'slug' => 'tas-ransel-outdoor-adventure',
                'description' => 'Ransel outdoor dengan kapasitas besar untuk hiking dan camping. Tahan air dan sangat kuat.',
                'price' => 750000,
                'discount_price' => 699000,
                'stock' => 12,
                'image' => 'https://images.unsplash.com/photo-1622560480654-d96214fdc887?w=400&h=400&fit=crop',
                'brand' => 'MountainPro',
                'material' => 'Ripstop Nylon',
                'color' => 'Hijau Army',
                'size' => '60 x 35 x 25 cm',
                'is_featured' => true,
                'is_active' => true,
            ],

            // Tas Selempang
            [
                'category_id' => 2,
                'name' => 'Tas Selempang Pria Modern',
                'slug' => 'tas-selempang-pria-modern',
                'description' => 'Sling bag modern untuk pria dengan desain minimalis dan fungsional. Cocok untuk daily use.',
                'price' => 320000,
                'discount_price' => 279000,
                'stock' => 28,
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
                'brand' => 'ModernMan',
                'material' => 'Canvas Premium',
                'color' => 'Hitam',
                'size' => '28 x 22 x 10 cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Tas Selempang Kulit Vintage',
                'slug' => 'tas-selempang-kulit-vintage',
                'description' => 'Messenger bag kulit dengan style vintage yang timeless. Semakin lama semakin bagus.',
                'price' => 680000,
                'discount_price' => 599000,
                'stock' => 15,
                'image' => 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop',
                'brand' => 'VintageLeather',
                'material' => 'Genuine Leather',
                'color' => 'Coklat Vintage',
                'size' => '32 x 25 x 8 cm',
                'is_featured' => true,
                'is_active' => true,
            ],

            // Tas Tote
            [
                'category_id' => 3,
                'name' => 'Tas Tote Canvas Minimalis',
                'slug' => 'tas-tote-canvas-minimalis',
                'description' => 'Tote bag canvas dengan desain minimalis dan eco-friendly. Perfect untuk shopping atau kuliah.',
                'price' => 180000,
                'discount_price' => 149000,
                'stock' => 40,
                'image' => 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400&h=400&fit=crop',
                'brand' => 'EcoBag',
                'material' => 'Canvas Organic',
                'color' => 'Natural',
                'size' => '38 x 32 x 10 cm',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Tas Tote Kerja Profesional',
                'slug' => 'tas-tote-kerja-profesional',
                'description' => 'Tote bag profesional untuk wanita karir. Elegan dan dapat memuat laptop 13 inch.',
                'price' => 420000,
                'discount_price' => 379000,
                'stock' => 22,
                'image' => 'https://images.unsplash.com/photo-1564422170194-896b89110ef8?w=400&h=400&fit=crop',
                'brand' => 'CareerBag',
                'material' => 'Saffiano Leather',
                'color' => 'Navy Blue',
                'size' => '42 x 35 x 12 cm',
                'is_featured' => true,
                'is_active' => true,
            ],

            // Tas Kulit
            [
                'category_id' => 4,
                'name' => 'Tas Kulit Formal Pria',
                'slug' => 'tas-kulit-formal-pria',
                'description' => 'Briefcase kulit untuk pria dengan desain formal dan profesional. Cocok untuk meeting dan kantor.',
                'price' => 950000,
                'discount_price' => 850000,
                'stock' => 8,
                'image' => 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=400&h=400&fit=crop',
                'brand' => 'ExecutiveBag',
                'material' => 'Full Grain Leather',
                'color' => 'Hitam',
                'size' => '40 x 30 x 10 cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Tas Kulit Wanita Mewah',
                'slug' => 'tas-kulit-wanita-mewah',
                'description' => 'Handbag kulit premium untuk wanita dengan desain mewah dan elegan. Limited edition.',
                'price' => 1200000,
                'discount_price' => 1099000,
                'stock' => 5,
                'image' => 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=400&h=400&fit=crop',
                'brand' => 'LuxuryBag',
                'material' => 'Italian Leather',
                'color' => 'Burgundy',
                'size' => '32 x 28 x 14 cm',
                'is_featured' => true,
                'is_active' => true,
            ],

            // Tas Travel
            [
                'category_id' => 5,
                'name' => 'Tas Travel Cabin Size',
                'slug' => 'tas-travel-cabin-size',
                'description' => 'Tas travel ukuran cabin yang bisa dibawa ke pesawat. Praktis dengan roda dan handle.',
                'price' => 580000,
                'discount_price' => 529000,
                'stock' => 18,
                'image' => 'https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=400&h=400&fit=crop',
                'brand' => 'TravelEase',
                'material' => 'Polycarbonate',
                'color' => 'Silver',
                'size' => '55 x 40 x 20 cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Tas Duffel Gym & Sport',
                'slug' => 'tas-duffel-gym-sport',
                'description' => 'Duffel bag untuk gym dan olahraga dengan kompartemen sepatu terpisah. Tahan air dan mudah dibersihkan.',
                'price' => 380000,
                'discount_price' => 339000,
                'stock' => 25,
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop',
                'brand' => 'SportBag',
                'material' => 'Polyester Waterproof',
                'color' => 'Hitam/Orange',
                'size' => '50 x 28 x 28 cm',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Tas Wanita
            [
                'category_id' => 6,
                'name' => 'Tas Wanita Mini Crossbody',
                'slug' => 'tas-wanita-mini-crossbody',
                'description' => 'Tas mini crossbody yang cute dan praktis untuk hangout. Desain trendy dan warna-warna cerah.',
                'price' => 220000,
                'discount_price' => 189000,
                'stock' => 32,
                'image' => 'https://images.unsplash.com/photo-1564422170194-896b89110ef8?w=400&h=400&fit=crop',
                'brand' => 'CuteBag',
                'material' => 'PU Leather',
                'color' => 'Pink Pastel',
                'size' => '20 x 15 x 8 cm',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 6,
                'name' => 'Tas Wanita Clutch Party',
                'slug' => 'tas-wanita-clutch-party',
                'description' => 'Clutch bag elegan untuk acara formal dan pesta. Dilengkapi dengan rantai emas yang bisa dilepas.',
                'price' => 350000,
                'discount_price' => 299000,
                'stock' => 15,
                'image' => 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=400&h=400&fit=crop',
                'brand' => 'PartyBag',
                'material' => 'Satin Premium',
                'color' => 'Gold',
                'size' => '25 x 15 x 5 cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 6,
                'name' => 'Tas Wanita Shoulder Bag',
                'slug' => 'tas-wanita-shoulder-bag',
                'description' => 'Shoulder bag dengan desain klasik yang cocok untuk segala acara. Material berkualitas tinggi.',
                'price' => 480000,
                'discount_price' => 429000,
                'stock' => 20,
                'image' => 'https://images.unsplash.com/photo-1564422170194-896b89110ef8?w=400&h=400&fit=crop',
                'brand' => 'ClassicBag',
                'material' => 'Synthetic Leather',
                'color' => 'Camel',
                'size' => '28 x 22 x 10 cm',
                'is_featured' => true,
                'is_active' => true,
            ],

            // Tambahan Produk Premium
            [
                'category_id' => 1,
                'name' => 'Tas Ransel Anti Maling',
                'slug' => 'tas-ransel-anti-maling',
                'description' => 'Ransel dengan fitur anti-theft, hidden zipper, dan RFID protection. Aman untuk traveling.',
                'price' => 620000,
                'discount_price' => 569000,
                'stock' => 16,
                'image' => 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop',
                'brand' => 'SecureBag',
                'material' => 'Oxford Fabric',
                'color' => 'Dark Grey',
                'size' => '46 x 30 x 16 cm',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Tas Selempang Tablet',
                'slug' => 'tas-selempang-tablet',
                'description' => 'Sling bag khusus untuk tablet dan iPad dengan padding empuk. Desain slim dan modern.',
                'price' => 290000,
                'discount_price' => 259000,
                'stock' => 24,
                'image' => 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=400&h=400&fit=crop',
                'brand' => 'TechBag',
                'material' => 'Neoprene',
                'color' => 'Charcoal',
                'size' => '26 x 20 x 4 cm',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Tas Tote Laptop 15 inch',
                'slug' => 'tas-tote-laptop-15-inch',
                'description' => 'Tote bag dengan kompartemen laptop 15 inch. Stylish dan fungsional untuk profesional muda.',
                'price' => 450000,
                'discount_price' => 399000,
                'stock' => 19,
                'image' => 'https://images.unsplash.com/photo-1564422170194-896b89110ef8?w=400&h=400&fit=crop',
                'brand' => 'WorkBag',
                'material' => 'Canvas & Leather',
                'color' => 'Grey/Brown',
                'size' => '40 x 32 x 12 cm',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('Successfully added ' . count($products) . ' more products!');
    }
}
